import { SpreadsheetRow } from './types';

export const INITIAL_SPREADSHEET_DATA: SpreadsheetRow[] = [
  {
    id: "1",
    category: "LUPA PASSWORD",
    url: "https://wdbos90.com/#/forget",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "2",
    category: "HUBUNGI KAMI",
    url: "https://wdbos90.com/#/service",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "3",
    category: "PREDIKSI BOLA",
    url: "https://wdbos90.com/blog/?title=PREDIKSI%20BOLA%20WDBOS",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "4",
    category: "RTP SLOT",
    url: "https://wdbos90.com/rtp/",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "5",
    category: "CARA BERMAIN",
    url: "https://wdbos90.com/#/gameRules",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "6",
    category: "BUKTI JP",
    url: "https://wdbos90.com/blog/?categories=BUKTI%20JP",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "7",
    category: "PENGADUAN CUSTOMER",
    url: "https://wdbos90.com/#/index?category=hot",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "8",
    category: "YOUTUBE",
    url: "https://www.youtube.com/channel/UCPvCLIOIpq8ItGmcW-iCgwg?themeRefresh=1",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "9",
    category: "FACEBOOK",
    url: "https://www.facebook.com/wdbos888?rdid=BE7ULcomb6m1CNDM&share_url=https%3A%2F%2Fwww.facebook.com%2Fshare%2F1ET3FYxgUf%2F#",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "10",
    category: "TWITTER",
    url: "https://x.com/wdbos252",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "11",
    category: "TELEGRAM",
    url: "https://t.me/wdbosnew88_bot",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "12",
    category: "WHATSAPP CHANNEL",
    url: "https://www.whatsapp.com/channel/0029Vb8RagH6LwHt3GNo6v17",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "13",
    category: "FACEBOOK GROUP",
    url: "https://www.facebook.com/groups/1857154468262416",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "14",
    category: "LIVECHAT",
    url: "https://direct.lc.chat/14748282",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "15",
    category: "INSTAGRAM",
    url: "",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "16",
    category: "PROMOSI SITUS",
    url: "https://wdbos90.com/#/activity",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "17",
    category: "PROMOSI PROVIDER",
    url: "",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "18",
    category: "DAFTAR",
    url: "https://wdbos90.com/#/register",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "19",
    category: "PERATURAN PERMAINAN",
    url: "",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "20",
    category: "LOGIN & SAYA SETUJU",
    url: "",
    username: "",
    password: "",
    requiresLogin: true,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "21",
    category: "LUCKY WHEEL",
    url: "",
    username: "",
    password: "",
    requiresLogin: true,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "22",
    category: "PROFIL",
    url: "https://wdbos90.com/#/mine",
    username: "",
    password: "",
    requiresLogin: true,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "23",
    category: "HISTORY TARUHAN",
    url: "https://wdbos90.com/#/betRecords",
    username: "",
    password: "",
    requiresLogin: true,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "24",
    category: "PERHITUNGAN HADIAH TOGEL",
    url: "https://wdbos90.com/#/lotteryCalculate",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "25",
    category: "PREDIKSI TOGEL",
    url: "https://wdbos90.com/blog/?title=PREDIKSI%20TOGEL%20WDBOS",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "26",
    category: "PESAN SAYA",
    url: "https://wdbos90.com/#/myMessage",
    username: "",
    password: "",
    requiresLogin: true,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "27",
    category: "REFFERAL",
    url: "https://wdbos90.com/#/myRecommend",
    username: "",
    password: "",
    requiresLogin: true,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "28",
    category: "KYC",
    url: "https://wdbos90.com/#/myKYC",
    username: "",
    password: "",
    requiresLogin: true,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "29",
    category: "BONUS",
    url: "https://wdbos90.com/#/transactionRecords?Bonus",
    username: "",
    password: "",
    requiresLogin: true,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "30",
    category: "LOGOUT",
    url: "https://wdbos90.com/#/index?category=history",
    username: "",
    password: "",
    requiresLogin: true,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "31",
    category: "PENARIKAN CASH",
    url: "https://wdbos90.com/#/withdrawal",
    username: "",
    password: "",
    requiresLogin: true,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "32",
    category: "PENARIKAN USDT",
    url: "https://wdbos90.com/#/withdrawal",
    username: "",
    password: "",
    requiresLogin: true,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "33",
    category: "DEPOSIT",
    url: "https://wdbos90.com/#/deposit",
    username: "",
    password: "",
    requiresLogin: true,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "34",
    category: "BARCODE QRIS",
    url: "https://wdbos90.com/#/deposit",
    username: "",
    password: "",
    requiresLogin: true,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "35",
    category: "JADWAL PASARAN TOGEL",
    url: "https://wdbos90.com/#/index?category=lottery",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "36",
    category: "HADIAH TOGEL",
    url: "https://wdbos90.com/blog/?title=HADIAH%20TOGEL%20WDBOS",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "37",
    category: "JADWAL BANK",
    url: "https://wdbos90.com/blog/?categories=Jadwal%20Bank",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "38",
    category: "SYAIR",
    url: "https://wdbos90.com/blog/?categories=SYAIR",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "39",
    category: "CARA BETTING TOGEL",
    url: "https://wdbos90.com/blog/?title=CARA%20BETTING%20TOGEL",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "40",
    category: "HISTORY NOMOR",
    url: "https://randomtechhub.com/?gameid=54#/historyNomor",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "41",
    category: "BUKU MIMPI",
    url: "",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "42",
    category: "PROMOSI SPESIAL",
    url: "https://wdbos90.com/#/activity",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "43",
    category: "MENU GAMES (CEK 1 1)",
    url: "",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "44",
    category: "TOGEL ALL PASARAN",
    url: "https://wdbos90.com/#/index?category=lottery",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "45",
    category: "SPINEMAN",
    url: "https://ruevop.com/ifm.html",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "46",
    category: "LUCKY DRAGON TIGER LIVE GAMES",
    url: "https://rebrand.ly/du4usn6",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "47",
    category: "LUCKY BACCARAT LIVE GAMES",
    url: "https://rebrand.ly/rsl83qt",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "48",
    category: "LIVEGAME PRAGMATIC PLAY LIVE GAMES",
    url: "https://wdbos90.com/#/game?category=live&code=ppLive&typeId=1808235",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "49",
    category: "PASSO V LIVE GAMES",
    url: "https://www.passo-game.com/Games/lobby.aspx?lang=id&section=hot",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "50",
    category: "EVOLUTION LIVE GAMES",
    url: "https://tmphnxsea.ps9launcher.com/frontend/evo/mini/#category=all_games",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "51",
    category: "SEXYGAMING LIVE GAMES",
    url: "https://bpweb.wlyss.net/player/webMain.jsp?dm=1&title=1",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "52",
    category: "EMPIRE GAMING LIVE GAMES",
    url: "https://fl.empiregaming.io/lobby",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "53",
    category: "TGION LIVE GAMES",
    url: "https://wwwpo1c1.t38games.com/web-page/general/tablet/default.aspx?token=IiOsbGd2QRdvo7q2w9j+bkMavHMGZF7SK4lmWeL4O9PXlo6sPICmAc8KEMhxpNeEQL+5FmpVvJ/3a7YehDG5LQ==&redir=PO1&isRedir=yes&product=1#/",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "54",
    category: "SA GAMING LIVE GAMES",
    url: "https://wdbos90.com/#/game?category=live&code=saLv&typeId=9655",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "55",
    category: "BG LIVE GAMES",
    url: "https://cdnx-hw.yctkrs.com/h5V01/pc/index.html?locale=en_US&mode=9&token=ht12482C858116A33899EA2D5D574941&uid=1210877313&account=1_wdbostes99&sn=ht12&referrer=https://wdbos90.com/",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "56",
    category: "PLAYTECH LIVE GAMES",
    url: "https://wdbos90.com/#/game?category=live&code=playtechLive&typeId=3228206",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "57",
    category: "MICROGAMING LIVE GAMES",
    url: "https://wdbos90.com/#/game?category=live&code=microLive&typeId=3376034",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "58",
    category: "PRAGMATIC PLAY SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=ppSlot&typeId=10183",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "59",
    category: "PG SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=pgSlot&typeId=9704",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "60",
    category: "PNG SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=yesSlot&typeId=9685",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "61",
    category: "NOLIMITCITY SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=evonlc&typeId=508286",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "62",
    category: "JILI SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=jiliSlot&typeId=552271",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "63",
    category: "ASK SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=askSlot&typeId=1927017",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "64",
    category: "GGSOFT SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=ggSoft&typeId=2417093",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "65",
    category: "HABANERO SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=habaneroSlot&typeId=1145817",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "66",
    category: "5G SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=5gSlot&typeId=1624015",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "67",
    category: "FATPANDA SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=fpSlot&typeId=2194299",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "68",
    category: "SPADEGAMING SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=sgSlot&typeId=3334040",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "69",
    category: "PLAYTECH SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=playtechSlot&typeId=2916756",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "70",
    category: "WOWGAMING SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=wowgaming&typeId=2420896",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "71",
    category: "HACKSAW SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=IMone&typeId=1984277",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "72",
    category: "PLAYSTAR SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=playStar&typeId=2410414",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "73",
    category: "RED TIGER SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=evoredtiger&typeId=508363",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "74",
    category: "NETENT SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=evonetent&typeId=5080",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "75",
    category: "BIGTIMEGAMING SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=evobtg&typeId=508051",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "76",
    category: "JOKER SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=jokerSlot&typeId=9925",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "77",
    category: "WMC SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=wmcSlot&typeId=9849",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "78",
    category: "MICROGAMING SLOT",
    url: "https://wdbos90.com/#/game?category=elgame&code=microSlot&typeId=3376097",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "79",
    category: "BESOFT",
    url: "https://wdbos90.com/#/game?category=elgame&code=besoftSlot&typeId=3243907",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "80",
    category: "SABA",
    url: "https://i7f2oa.bp145b4u.com/(S(Tesqedixd2c99fc589434110a7d86220d7872ffe))/NewIndex?lang=id&webskintype=3&scmt=tab02&ssmt=tab02",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "81",
    category: "SBO",
    url: "https://sports-sbomaind-play.llkkbbzz22.com/SBOMainD/ID_ID?token=1159834431.shzajRAOXjAgHYDeHfCcgs.241&host=sportsbook-auth.llkkbbzz22.com&loginname=5601849d56ee62947bbea66f1b7be1cb&jd=jd",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "82",
    category: "AP",
    url: "https://wyfunom.eviran66.com/id/compact/sports/soccer",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "83",
    category: "TF",
    url: "https://gc.9wwu88.com/v8/events",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "84",
    category: "JILI FISHING",
    url: "https://wdbos90.com/#/game?category=fish&code=jiliFish&typeId=552407",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "85",
    category: "BG FISHING",
    url: "https://wdbos90.com/#/game?category=fish&code=bgFish&typeId=23693",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "86",
    category: "JOKER FISHING",
    url: "https://wdbos90.com/#/game?category=fish&code=jokerFish&typeId=10122",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "87",
    category: "ASK FISHING",
    url: "https://wdbos90.com/#/game?category=fish&code=askFish&typeId=1927013",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "88",
    category: "SPADEGAMING FISHING",
    url: "https://wdbos90.com/#/game?category=fish&code=sgFish&typeId=3334167",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  },
  {
    id: "89",
    category: "ARCADE",
    url: "https://wdbos90.com/#/index?category=card",
    username: "",
    password: "",
    requiresLogin: false,
    lastScreenshotTime: null,
    lastScreenshotUrl: null,
    status: "idle"
  }
];
